#+title:      My Pen And Paper RPG Ruleset
#+date:       [2022-10-03 Mo 13:19]

#+OPTIONS: toc:nil H:10 tex:t author:nil date:nil num:3
#+LaTeX_HEADER: \usepackage[a4paper, total={7in, 11in}]{geometry}
#+LaTeX_HEADER: \pagenumbering{gobble}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\itemsep}{0.mm}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{noitemsep}
#+LATEX_HEADER: \usepackage[table]{xcolor}

#+LATEX: {\rowcolors{1}{grey!20}{grey!10}

#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:   	body {
#+HTML_HEAD:		background-color: #ACF;
#+HTML_HEAD:		font-family: "Roboto","Arial",sans-serif;
#+HTML_HEAD:		margin-left: 20vw;
#+HTML_HEAD:		margin-right: 20vw;
#+HTML_HEAD:	}
#+HTML_HEAD:	tbody tr:nth-child(odd) {
#+HTML_HEAD:		background-color: ##9BF;
#+HTML_HEAD:	}
#+HTML_HEAD:	tbody tr:nth-child(even) {
#+HTML_HEAD:		background-color: #8AF;
#+HTML_HEAD:	}
#+HTML_HEAD:	tbody th {
#+HTML_HEAD:		background-color: #8AF;
#+HTML_HEAD:	}
#+HTML_HEAD:	thead th {
#+HTML_HEAD:		background-color: #8AF;
#+HTML_HEAD:	}
#+HTML_HEAD:	table {
#+HTML_HEAD:		background-color: #ACF;
#+HTML_HEAD:		border: 1px solid #000;
#+HTML_HEAD:		margin: 20px;
#+HTML_HEAD:        float: right;
#+HTML_HEAD:	}
#+HTML_HEAD:    .decorationright {
#+HTML_HEAD:		position: fixed;
#+HTML_HEAD:		right: 0;
#+HTML_HEAD:		top: 0;
#+HTML_HEAD:		height: 100%;
#+HTML_HEAD:		width: 20vw;
#+HTML_HEAD:		background-image: linear-gradient(to right, rgba(4,96,205,0), rgba(4,96,205,1));
#+HTML_HEAD:	}
#+HTML_HEAD:	.decorationleft {
#+HTML_HEAD:		position: fixed;
#+HTML_HEAD:		left: 0;
#+HTML_HEAD:		top: 0;
#+HTML_HEAD:		height: 100%;
#+HTML_HEAD:		width: 20vw;
#+HTML_HEAD:		background-image: linear-gradient(to right, rgba(4,96,205,1), rgba(4,96,205,0));
#+HTML_HEAD:	}
#+HTML_HEAD: </style>


* COMMENT TODOs
- Charakter rechner
- Geld anders darstellen?

* Rules

#+LATEX: \begin{multicols}{2}[]
** Character Values
*** Attributes
Attributes dedscribe a characters potential. The higher the value the greater things a character can achieve. There are the following 8 Attributes beloning to the 4 categories.

| *Category* | *Attribute* | *Description*             |
|------------+-------------+---------------------------|
| Physical   | Strength    | strength and hardyness    |
|            | Dexterity   | agility, speed, precision |
|------------+-------------+---------------------------|
| Mental     | Will        | percevirance, attention   |
|            | Intelect    | intellegence, knowledge   |
|------------+-------------+---------------------------|
| Sozial     | Empathy     | understanding people      |
|            | Charisma    | interacting with people   |
|------------+-------------+---------------------------|
| Resources  | Gear        | Gear you have prepared    |
|            | Finances    | Money and investments     |

#+ATTR_LATEX: :align c|l
| *Level* | *Grade*     |
|---------+-------------|
|       3 | Unskilled   |
|       5 | Beginner    |
|       7 | Experienced |
|       9 | Master      |
|      11 | Grandmaster |
|      13 | Legend      |

They determine the amount of dice you can use for [[#sec:checks][checks]]. 

*** Skill
The skill determines the likelyhood of a success on a roll. A roll during a [[#sec:checks][checks]] is counted as a success if the dice shows less or equal eyes than the skill.

Skills measure the mastery of a skill. They are expressed as a background description and a level (number between 1 and 6). The skill levels are comparable to how much time a typical person has to spend to reach the same expertise in this area if it were his dayjob. This does however not mean that a character needs to have taken that time to reach his skill level. Level 1 for any skill is free. Not all skills cost the same, the price depends on how specific it is.

#+ATTR_LATEX: :align c|l
| *Level* | *Equivalent experience* |
|-------+-----------------------|
|     1 | 0 years               |
|     2 | 2 years               |
|     3 | 5 years               |
|     4 | 10 years              |
|     5 | 15 years              |
|     6 | 20 years              |

See chapter [[#sec:loskills][List of Skills]] for examples.

*Merge Skills*
It might happen that you have a lot of very specific skills. If that is the case you can combine them to a more general skill. The total CP cost has to stay the same.

*** Traits
Traits are distinglishing things about the character. They can be bought for character points. This is possible both at character creation and later in the game.
 They might be extraordinary strength or the ability to cast certain magic. Some traits (like all magic) should come with a risk (all checks are risky checks). 

#+begin_quote
Herkulian Stength (7CP):
You are extra strong. For feats of strength you can roll 1 additional die and get at least one success.
#+end_quote

#+begin_quote
Pyromancy (7CP):
You can make a risky mental check to summon the primordial elemental forces of fire. You can shape and direct them to cause effects. 
#+end_quote

*** Character Creation
Distribute 110 CP on your Attributes, Skills and Traits

Use the Rules under Equipment to limit your starting gear.

Character Advancement:
You may reward your players with CP (character points) for reaching milestones in the story or simply surviving the session.

- A skill point typicaly costs 7 CP but can vary based on how specific they are.
- An attribute point costs 2 CP.
- A Trait typically costs 7 CP but can vary widely. Negative traits can even have a negative price.

** Checks and Contests
:PROPERTIES:
:CUSTOM_ID: sec:checks
:END:

Roll as many six sided dice as your attribute value is. Count each die with your skill level or less eyes and subtract the difficulty (default is 0) of the check. The result are your successes. If the successes are negative the check fails.

- Parties describe what they indent to do
- Parties decide (secretly) how many dice they want to use for each action
- Everybody rolles their dice
- Results of the checks are described. 

*Effects:*
- Every action has a default effect. For example in a fight it is wounding an enemy.
- Different effects can also be declared by the player. (e.g. disarming the enemy).
- Combinations are also possible
- An Effect might cost more than one success.

*Colaborative checks:*
Everyone rolls individually and then sum together all successes.

*Contest:*
Both parties each roll their check. the party with the higher successes wins and can use the difference in successes to declare effects. By default the effect is to damage the enemy.

*Risky checks:*
If a check is risky the character might incurr something bad if the check fails. If the check fails the difference between the negative successes are used to incur effects to the characters disadvantage. 

*Multible actions:*
You can perform multible actions. The checks are made independently. You can use at most the higher of the atributes numbers of dice in total. For each action your maximum number of dice is your respective attribute value. An common example is to use some of the action to attack and some to defend.

*Predefined Effekts:*
You can learn to achieve a certain combination of effects very effectively. You have to learn this as a trait. You can increase the difficulty of the check. Double the difficulty can be used to declare the predefined effects. The check automatically bekomes risky. This allows you to use the same dice to achieve multiple effects. Such a trait costs 1 CP.

*Concentration:*
Some effects have to be kept up. In those cases the successes needed to achieve the effect block the attribute points (dice) from being used for anything else, as long as the concentration lasts. 


This table gives an overview of what is a good difficulty for checks by average CP investment into attribute and skill, and what level of experience such a person would be described as having.
#+ATTR_LATEX: :align c|c|l
| *Dif* | *CP* | *Good for ..* |
|-------+------+---------------|
|     0 |   15 | unskilled     |
|     1 |   25 | beginner      |
|     2 |   30 | experienced   |
|     3 |   35 | master        |
|     4 |   40 | grand master  |
|     5 |   45 | legend        |
For an easy check select the difficulty 1 lower. For a hard check select a difficulty 1 higher.

For a list of effects see the section [[#sec:loeffects][List of Effects]]

** Damage
Damage reduces the attribute points (points) you can use. Damage is typically taken on attribute categories. If this is the case the victim can divide the damage aritrarily on the attributes in the category. Once your attribute effectively falls below 0 you are out of commision with regards to this attribute. The way in which you are taken out depends on the attribute and what caused the damage.

#+begin_quote
Bob the Barbarian got hit in combat multiple times. He has 4 Physical but 3 physical wounds. Now he additionally got confused by a spell and thinks his Comrades are enemys. His compatriot Roger the Rogue tries to nonlethaly take him out by hitting him with his blackjack over the head. He succeeds and makes another 2 damage. Bob goes down, bleeding from his old wounds but still alive.
#+end_quote

#+begin_quote
Silvia the Spy finds herself in a fierce debate with the Diplomat. She trys to convince him to go with her plan. Over the time she makes 3 social damage which is enough to convince him, as his social position is severely damaged by the documents she leaked a week ago.
#+end_quote

Depending on the source of the damage it might heal after each scene, mission or kampagnie.
- Scene: A thematically connected timeframe like a fight. (example: unarmed, blackjack, nets, drowning)
- Mission: Until a milestone in the game is reached, for example until the quest is finished or story beat is reached (example; sword, fire, knive, falling great heights)
- Kampagnie: Until a longterm goal is reached. For example until the evil King is vanquished. (example: nasgul blade, daemonic poison)
The short form to write this is 2s(/m/k) for two damage that heals by the end of the scene(/mission/kampagnie).
  
** Armor / Damage reduction
Armor or damage reduction (DR) does not negate damage completely but it changes its type to one that is faster to heal. With an armor of 2 up to 2m damage per contest are bein reduced to 2s damage. Normally damage reduction should only go down to scene level and not remove damage completely. As an optional rule however you can decide that scene damage can be reduced to nothing as long as at least 1 dmg stays. When considering armor always think about the complete set being worn and not about simgle pieces. Decide which armor class fits.

#+ATTR_LATEX: :align l|c
| *Armor Class* | *DR* |
|-------------+----|
| none        |  0 |
| light       |  1 |
| medium      |  2 |
| heavy       |  3 |

** Range
There are 3 different ranges. It takes one round and half your dice for this round to move one range class. You can however move within a range class unrestricted (within reason). While moving you can still use your action.

Close: Normal close quarters fighting distance.
Near: A distance you can throw something at.
Far: Quite a distance away. You might be able to shoot a rifle or a bow at this distance but it takes a while to run this distance.

** Items and Equipment

Items have a RV (Ressource Value) this determines how expensive or hard to get it is. Apart from that they have a description and maybe special effects. Let your fantasy go wild. A few examples can be found below.

An item can be found or bought. To buy an item you need to be somewhere where it is possible to be bought. Roll on Ressources. If you get at least the RV successes you have bought the item.

#+begin_quote
Sword (RV 2):
Its a stabby piece of metal. Especially good at harming unarmored enemies. Not so great at slicing though armor. 
#+end_quote

#+begin_quote
Chainmail (RV 3):
A metal fabric that protects your torso and arms from being cut or stabbed pretty well. 
#+end_quote

To create an item first give it a short description. It should make clear on what what kind of actions it may give advantages or what kind of effects may be created with it. Second you determine its RV (ressource value).
# - 0: Basically free: Everyone can aquire it if they want to (example: a club)
# - 1: Cheap: Even people with the lowest income will typically be able to affort this. (example: simple clothes, a fridge, a set of tools) 
# - 2: Affordable: (example: An appartment)
# - 3: Costly; (example: a regular house)
# - 4: Expensive: (example: Sportscar)
# - 5: Very expensive (example: a small airplane)
# - 6: Luxourious: This is something that only the very rich can affort (example: private jet)

#+ATTR_LATEX: :align c|l|l
| *RV* | *Description*  | *Example*                           |
|----+----------------+-------------------------------------|
|  0 | Free           | a club                              |
|  1 | Cheap          | simple clothes, basic tools         |
|  2 | Affordable     | regular car, appartment             |
|  3 | Costly         | regular house                       |
|  4 | Expensive      | sportscar                           |
|  5 | Very Expensive | small airplane                      |
|  6 | Luxourious     | private jet                         |


*** Equipment
Characters can have gear with a value of up to the attribute resources / 2 in RV on them. They must be able to carry all that gear on them or if it is part of their household it must fit in their normaly furnished home. Apply reason as necessary.

When out adventuring characters have all the gear that they have written down. Additionally they can be allowed to make a resources check against the RV of what they would like to have in the moment to see if they do. The check is risky and if they fail they get the difference in damage to their resources attribute until the end of the mission.

*** Buying
Characters can buy new stuff with a finances check against the RV of what they want to buy. The check is risky and they get the difference in damage on their finances until the end of the mission if they fail. The GM does not have to let you retry on a fail.

*** Crafting
Characters can also build their own items. For that they need the appropriate tools and resources. The resources may be bought for the RV-1 of the item to be build. To build the item the character needs to make a check with RV difficulty. If that fails the resoruces might be lost, depending on what they are.

*** Gathering
Resources can be gathered with a check and their RV as difficulty.

*** Bribing
To Bribe someone you need to give them more than they can normally compfortably afford. This means you need more than half their finances value in successes to bribe them.

#+LATEX: \newpage
* Lists

** List of Traits
:PROPERTIES:
:CUSTOM_ID: sec:lotraits
:END:

The list is not exaustive. It should only be taken as a list of examples.

#+begin_quote
*Friend of Nature* (7): You can talk to the forces of nature and have a chance to convince them to help you. This can be asking, a bird what he has seen, letting youself be concealed by a bush or calling a wild bear to aid you in combat.
#+end_quote

#+begin_quote
*Illusionist* (7): You are adapt at creating illusions. The bigger and more complex they get the harder this is.
#+end_quote

#+begin_quote
*Speedster* (14): You have incredible speed. Others see only a blur when you sprint past them. This often gives you an advantage on dexterity checks and you always have at least 1 success in them.
#+end_quote

#+begin_quote
*Medium* (7): You can commune with ghosts and spirits. You have no control over them, but you can gain their attention.
#+end_quote

#+begin_quote
*Nightvision* (7): You can see in darkness as if it were light.
#+end_quote

#+begin_quote
*Sleepless* (7): You dont need sleep. This means you have a lot more time in a day, but you still need to rest from to much physical or mental excertion.
#+end_quote

#+begin_quote
*Flight* (16): You can fly. Be it with wings or otherwise. Your speed in flight is no different from your speed on land.
#+end_quote

#+begin_quote
*Tinkerer* (7): You can build wonderous mechanikal marvels. From clocks up to steam powered automata. 
#+end_quote

#+begin_quote
*Hacker* (7): You are not only proficient in computer science but you can even achieve movie worthy feats like stoping another car with only your laptop during a car chase. Tools not included.
#+end_quote

#+begin_quote
*Plot Armor* (1): Each scene you can discard a point of damage you would take. The plot armor only allies to one of the categories (Physical, Mental, Sozial) This trait can be taken multiple times.
#+end_quote


** List of Skills
:PROPERTIES:
:CUSTOM_ID: sec:loskills
:END:

The list is not exaustive. It should only be taken as a list of examples. The CP costs are per level.

#+begin_quote
*Professional Chef* (7 CP): You have learned not only to cook but also to plan the foodstuffs on storage, to store propperly, to calucalte profitability, to motivate and coordinate a team of people.
#+end_quote

#+begin_quote
*Soldier* (7 CP): You have learned to bear harsh weather, climb over obstacles, run, dodge and shoot. You have learned dicipline and coordination.
#+end_quote

#+begin_quote
*Trouthsayer* (7 CP): You have learned to peer into possible futures, read people and make inferences on what will likely happen. You have learned the art of putting on an act. 
#+end_quote

#+begin_quote
*Ranger* (7 CP): You know how to survive in the wild. You can hunt, bushcraft and gather everything you need. You have honed your hearing and are proficient at tracking.
#+end_quote

#+begin_quote
*College Mage* (7 CP): You have studied the art of magic. You learned them with books, astronomy and experiments. You can cast spells by pronouncing incantations, magical glyphs and potent periphinalia. You still need the appropriate trait to cast magic from specific schools of magic.
#+end_quote

#+begin_quote
*Survivalist* (1 CP): You have spend quite a lot of time outdoors. Consumed books about wilderness survival and so on. You know how to build shelter, find food and water, and much more. 
#+end_quote


** List of Items
:PROPERTIES:
:CUSTOM_ID: sec:loitems
:END:

The list is not exaustive. It should only be taken as a list of examples.

#+begin_quote
*Club of the great Bear* (RV 4): A mystical club made from the thigh bone of the great bear that terrorized the inokwa people. It still contains the strength of the mighty beast. When using this club you gain 1 additional skill level in strength checks.
#+end_quote

#+begin_quote
*Knightly Armor* (RV 4): A good example of heavy armor that protects from physical damage from most weapons.
#+end_quote

#+begin_quote
*Protective Amulet* (RV 2): This amulet made from magicaly potent elderwood protects lightly (1 damage reduction) from mental damge comming from magic.
#+end_quote

#+begin_quote
*Pentagram Amulet* (RV 2): This amulet was made to prevent possession and influence of otherworldly forces. Allows you to rerol 1 die against attacks against your mental state when comming from ghosts, magic, or similar forces.
#+end_quote

#+begin_quote
*Potion of Healing* (RV 3): When being drunk it allows you to reduce the healing time of up to 4 physical damage from M to S
#+end_quote

#+begin_quote
*Shield* (RV 2): Gives the reroll of 1 die when blocking with the shield.
#+end_quote

#+begin_quote
*Sword* (RV 2): This stabby piece of steel typically makes class M damage. Its also good at slicing.
#+end_quote

** List of Effects
:PROPERTIES:
:CUSTOM_ID: sec:loeffects
:END:

#+begin_quote
*Damage:* Each success is used to cause 2 damage to an enemy.
#+end_quote

#+begin_quote
*Block:* Each success is used to remove one success from an enemies attack on you or one of your collegues. If you win a contest with a block you can deal 1 damage per success (type appropriate to the weapon used). If an enemies block would deal damage to you it can also be blocked.
#+end_quote

#+begin_quote
*Disarm:* For 2 successes disarm one enemy.
#+end_quote

#+begin_quote
*Push:* For 1 success you can force your enemy to move slightly. Pushing an ememy off a cliff still gives them a check to prevent them from falling.
#+end_quote

#+begin_quote
*Disable:* You can force an enemy into an unfavorable position. For each 2 successes the enemy is denied to use one level of his applicable skill. The enemy can recover from this with a check. The DM decides if this recovery can be blocked. Example: Putting the enemy into an ankle lock.
#+end_quote

#+begin_quote
*Gain Advantage:* For 1 success each you can make your position more advantageous. This allows you to reroll 1 die on applicable checks until the end of the scene. Examples: Gaining the high ground, flanking the enemy.
#+end_quote

#+begin_quote
*Cause Disadvantage:* For 1 success each you can make the enemys position more disadvantageous. This means he has to rerol 1 die that would otherwise be a success until the end of the scene. Example: Forcing the emeny into a tight corner. 
#+end_quote

#+begin_quote
*Blind:* For 2 successes. Take an emenys sense. Examples: Throw sand into eyes, Shatter eardrums with a lound noise.
#+end_quote

#+begin_quote
*Summon:* Per success the summoned being has 10 CP. The summon holds until the end of the scene or until the end of the concentration.
#+end_quote

#+begin_quote
*Obfuscate Area:* Per 4 successes you can obfuscate an area with regards to one sense. For example by causing total darkness or stopping all sound. The effect holds until the end of the scene or until the end of the concentration.
#+end_quote

#+begin_quote
*Purify Thing:* Per success you can purify one unit of a non sentient thing. For example remove poisons from one days worth of food, or remove the daemonic blight from a couple trees in the forrest.
#+end_quote

#+begin_quote
*Amplify Aspect:* Per 2 successes you increase an inherent aspect of a thing by 1 level. An example is increasing the protection of an armor by 1 or increasing the weight of a stone.
#+end_quote

#+begin_quote
*Buff:* For 1 success increase an attribute by 1. The effect holds until the end of the scene or until the end of the concentration.
#+end_quote

#+begin_quote
*Shapeshift:* Take the form of another being. The new forms max CP depends on the sucesses. Per success get 15 CP (max is the characters total CP). The effect holds until the end of the scene or until the end of the concentration.
#+end_quote

#+begin_quote
*Illusion:*
#+end_quote

#+begin_quote
*Deceive:* 
#+end_quote

#+begin_quote
*Influence:* 
#+end_quote

#+begin_quote
*Shape Reality:* 
#+end_quote

#+begin_quote
*Move:* Be it teleportation or a magic portal. 
#+end_quote

#+begin_quote
*Heal:* Per success turn 1m damage to 1s damage.
#+end_quote

#+begin_quote
*Counter/Break:* Counter or break a spell or technique.
#+end_quote

#+begin_quote
*Insight:* 
#+end_quote

#+begin_quote
*Stop:* 
#+end_quote

#+begin_quote
*:* 
#+end_quote

#+begin_quote
*:* 
#+end_quote


** List of NPCs
:PROPERTIES:
:CUSTOM_ID: sec:lonpcs
:END:

#+begin_quote
*Goblin* (34 CP)
P:2, M:1, S:1, R:1, Bandit 2, Nightvision
#+end_quote

#+begin_quote
*Wolf* (38 CP)
P:3, M:1, S:2, R:0, Packhunter 3
#+end_quote

#+begin_quote
*Guard* (76 CP)
P:4, M:4, S:4, R:4, Cityguard 3
#+end_quote

#+begin_quote
*Dark Mage* (125 CP)
P:3, M:8, S:4, R:6, Necromancer 3, Telepathic Link to undead servants
#+end_quote

#+begin_quote
*Ogre* (90 CP)
S:16, D:8, W:6, I:2, E:2 ,C:2, G:1, F:1, Ogre Stuff: 3
#+end_quote

#+begin_quote
*Zombie* (31 CP)
P:3, M:1, S:1, R:1, Infectious Bite
#+end_quote

#+LATEX: \newpage
* Optional Rules

** Less precise Attributes
Instead of using the Attributes as listed you can use only the Categories. Learning a level in one of the categories costs duble of what a level in an attribute would cost.

** No Abstraction for Money
To remove the resources category from the attributes just raise the price of learning a level of the other attributes by 33%. The costs for goods and services depend on the kampaign setting.

** Fixed spells with optional free casting of magic
If you want spells in general to be predefined but still allow for free casting from time to time you can use the fixed spells optional rules and add the following. When free casting magic you dont need to have the trait for the spell and can even create the spell on the fly, but all effects cost double the successes on a roll. All magic checks stay risky.

** Fixed spells
If you dont want PCs to be able to create situation specific spells then you can disallow it. Instead you need to define for every spell what effects they cause. Look at the rules for contests for guidance. The difficulty of the spell should be the ammount of successes you would have needed to cause those effects. To learn a spell the player has to aquire it as a trait. Such a trait can be comparatively cheap though (1-5 CP depending on how many spells you want to exist). All spell checks are risky checks.

** Retroactive Actions
The DM may allow players retroactively having performed some action. For example having placed a trap beforehand. To balance this any check on such an action should be a risky check.

** Too Many Dice
It can happen that you have to roll to many dice at once. If that happens your can instead divide the number of dice by a number (2,3,4) and multiply the number of successes by that number. If the dice are not evenly divisible just roll the rest regularly. It is advisable to use this method if the number of dice exeeds 12.

** Exhausting Combat
To limit the duration of a combat scene apply this rule. If in one round no party takes any damage, then apply 1s damage to each combatant. 

#+LATEX: \end{multicols}

* COMMENT Playtest questions
Should you be able to move and act in a single round?

For initative should all move at once or should we use group initiative?

Does the money and item system feel good?
